# Generated by Django 3.1.2 on 2020-10-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv_generator_app', '0003_auto_20201013_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
