# Generated by Django 3.1.2 on 2020-10-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv_generator_app', '0004_profile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.AddField(
            model_name='profile',
            name='blog',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_university',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_year',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience1_company',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience1_role',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience1_summary',
            field=models.TextField(default='', editable=False, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience1_year',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience2_company',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience2_role',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience2_summary',
            field=models.TextField(default='', editable=False, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience2_year',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience3_company',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience3_role',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience3_summary',
            field=models.TextField(default='', editable=False, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience3_year',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience4_company',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience4_role',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience4_summary',
            field=models.TextField(default='', editable=False, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience4_year',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(default='', editable=False, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.TextField(default='', editable=False, max_length=2000),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='web_cv_photo.jpg', upload_to='.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_board',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_year',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='your_place',
            field=models.CharField(default='anonymous', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='anonymous', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(default='', editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(default='', editable=False, max_length=2000),
        ),
    ]
