# Generated by Django 3.1.2 on 2020-10-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv_generator_app', '0005_auto_20201016_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
