# Generated by Django 3.1.2 on 2020-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv_generator_app', '0013_auto_20201016_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blog',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience1_company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience1_role',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience1_summary',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience1_year',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='your_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
