# Generated by Django 3.1.2 on 2020-10-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv_generator_app', '0014_auto_20201016_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='web_cv_photo.jpg', upload_to='media/'),
        ),
    ]
