# Generated by Django 3.1.2 on 2020-11-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_cv_generator_app', '0025_auto_20201120_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
